import React from "react";
import { Inter } from "next/font/google";
import { LoginProvider } from "../context/LoginContext";
import AppBar from "../components/Appbar";
import { cookies } from "next/headers"; 
import { decode_jwt, validate_jwt } from "@falgunpal/jwt-helper-ts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quadiro",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // Extract cookies on the server side
  const cookiesList = cookies();
  const token = cookiesList.get("token")?.value;
  const login = token ? validate_jwt(process.env.NEXT_PUBLIC_JWT_SECRET as string, token) : false;

  
  let role = "";
  if (token && process.env.NEXT_PUBLIC_JWT_SECRET) {
    const { payload } = decode_jwt(process.env.NEXT_PUBLIC_JWT_SECRET, token);
    role = payload.role;
  }

  return (
    <html lang="en" style={{overflowX:"hidden" }}>
      <body style={{ margin: 0, overflowX:"hidden" }} className={inter.className}>
        <LoginProvider initialLogin={login} initialRole={role}>
          <AppBar>{children}</AppBar>
        </LoginProvider>
      </body>
    </html>
  );
}
